homework_08/blog/blog_django_app/urls.py
from django.urls import path

from .views import (
    UserListView,
    PostListView,
    PostDetailsView,
    UserDetailsView,
)

app_name = "blog_django_app"

urlpatterns = [
    path('users/', UserListView.as_view(), name="users"),
    path('users/<int:pk>/', UserDetailsView.as_view(), name="user_details"),
    path('posts/', PostListView.as_view(), name="posts"),
    path('posts/<int:pk>/', PostDetailsView.as_view(), name="post_details"),
]

homework_08/blog/blog_django_app/views.py
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import User, Post


class UserListView(ListView):
    queryset = User.objects.filter(is_staff=False)
    template_name = "blog/users.html"


class PostListView(ListView):
    queryset = Post.objects.select_related("user")
    template_name = "blog/posts.html"


class PostDetailsView(DetailView):
    queryset = Post.objects.select_related("user")
    template_name = "blog/post_details.html"


class UserDetailsView(DetailView):
    model = User
    template_name = "blog/user_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_posts"] = Post.objects.filter(user=self.object).all()
        return context

homework_08/blog/blog_django_app/templates/blog/post_details.html
{% extends 'blog/base.html' %}

{% block title %}
  Post #{{ post.id }}
{% endblock %}

{% block body %}
  <h1>
    Post "{{ post.title|title }}"
    by <a href="{% url 'blog_django_app:user_details' pk=post.user.id %}">{{ post.user.username }}</a>
  </h1>

  <div>
    <p>{{ post.body }}</p>
  </div>

  <br>
  <div>
    <a class="btn btn-dark" href="{% url 'blog_django_app:posts' %}">All posts.</a>
  </div>


{% endblock %}

homework_08/blog/blog_django_app/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% block title %}
  Posts List
{% endblock %}

{% block body %}
  <h1>Posts: </h1>

  {% if post_list %}
    <ul class="list-group">
      {% for post in post_list %}
        <li class="list-group-item">
          <a class="text-decoration-none">
            <strong>
              <a href="{% url 'blog_django_app:post_details' pk=post.id %}">"{{ post.title }}"</a>
            </strong>  by {{ post.user.username }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <div>
      <strong>No posts.</strong>
    </div>
  {% endif %}

{% endblock %}

homework_08/blog/blog_django_app/templates/blog/user_details.html
{% extends 'blog/base.html' %}

{% block title %}
  User #{{ user.id }}
{% endblock %}

{% block body %}
  <h1>
    User {{ user.username }}
  </h1>

  <div>
    <strong>About {{ user.username }}</strong>:
    <p>{{ user.about }}</p>
  </div>

  {% if user_posts %}
    <h2>
      {{ user.username }}'s posts:
    </h2>
    <ul class="list-group">
      {% for post in user_posts %}
        <li class="list-group-item">
          <a class="text-decoration-none" href="{% url 'blog_django_app:post_details' pk=post.id %}">
            {{ post.title }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <div>
      <strong>No posts.</strong>
    </div>
  {% endif %}

  <br>
  <div>
    <a class="btn btn-dark" href="{% url 'blog_django_app:users' %}">All users.</a>
  </div>


{% endblock %}

homework_08/blog/blog_django_app/templates/blog/users.html
{% extends 'blog/base.html' %}

{% block title %}
  Users List
{% endblock %}

{% block body %}
  <h1>Users: </h1>

  {% if object_list %}
    <ul class="list-group">
      {% for user in object_list %}
        <li class="list-group-item">
          <a class="text-decoration-none" href="{% url 'blog_django_app:user_details' pk=user.id %}">
            {{ user.username }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <div>
      <strong>No users.</strong>
    </div>
  {% endif %}

{% endblock %}