homework_09/blog/blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('blog_django_app.urls')),
    path('accounts/', include('blog_authorization.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

homework_09/blog/blog_authorization/urls.py
from django.urls import path

from .views import UserCreationView, LogoutView, LoginView


urlpatterns = [
    path('register/', UserCreationView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

homework_09/blog/blog_django_app/urls.py
from django.urls import path

from .views import (
    UserListView,
    PostListView,
    PostDetailsView,
    UserDetailsView,
    PostCreateView,
    PostDeleteView,
)

app_name = "blog_django_app"

urlpatterns = [
    path('users/', UserListView.as_view(), name="users"),
    path('users/<int:pk>/', UserDetailsView.as_view(), name="user_details"),
    path('posts/', PostListView.as_view(), name="posts"),
    path('posts/<int:pk>/', PostDetailsView.as_view(), name="post_details"),
    path('post-creation/', PostCreateView.as_view(), name="post_creation"),
    path('posts/<int:pk>/delete-post/', PostDeleteView.as_view(), name="post_delete"),
]

homework_09/blog/blog_authorization/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from django.dispatch import receiver

UserModel: User = get_user_model()


class UserProfile(models.Model):
    user: UserModel = models.OneToOneField(
        UserModel,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    bio = models.TextField(max_length=300, blank=True)

    def __str__(self):
        return f"{self.user.username} profile"


@receiver(post_save, sender=UserModel)
def user_saved_handler(instance: UserModel, created: bool, **kwargs):
    if not created:
        return

    UserProfile.objects.create(user=instance)

homework_09/blog/blog_django_app/models.py
from django.contrib.auth.models import User
from django.db import models


# class User(models.Model):
#     name = models.CharField(max_length=64, unique=True)
#     email = models.CharField(null=False, max_length=32, unique=True)
#     about = models.TextField(blank=True, null=False, max_length=500)
#
#     def __str__(self):
#         return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField(blank=True, max_length=2000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

homework_09/blog/blog_authorization/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

homework_09/blog/blog_django_app/forms.py
from django.forms import ModelForm, CharField

from .models import Post


class PostCreationForm(ModelForm):

    class Meta:
        model = Post
        fields = "title", "body"

homework_09/blog/blog_authorization/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import (
    LogoutView as LogoutViewGeneric,
    LoginView as LoginViewGeneric,
)

from .forms import UserCreationForm
from .models import UserModel


class UserCreationView(CreateView):
    model = UserModel
    success_url = reverse_lazy("blog_django_app:users")
    form_class = UserCreationForm
    template_name = "blog_authorization/register.html"


class LoginView(LoginViewGeneric):
    next_page = reverse_lazy("blog_django_app:users")
    template_name = "blog_authorization/login.html"


class LogoutView(LogoutViewGeneric):
    next_page = reverse_lazy("blog_django_app:users")

homework_09/blog/blog_django_app/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin


from .forms import PostCreationForm
from .models import User, Post


class UserListView(ListView):
    queryset = User.objects.filter(is_staff=False)
    template_name = "blog/users.html"


class PostListView(ListView):
    queryset = Post.objects.select_related("user")
    template_name = "blog/posts.html"


class PostDetailsView(DetailView):
    queryset = Post.objects.select_related("user")
    template_name = "blog/post_details.html"


class UserDetailsView(DetailView):
    model = User
    template_name = "blog/user_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_posts"] = Post.objects.filter(user=self.object).all()
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = "blog/post_creation.html"

    def get_success_url(self):
        return reverse("blog_django_app:post_details", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        self.object: Post = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("blog_django_app:posts")
    template_name = "blog/post_confirm_delete.html"

homework_09/blog/blog_authorization/templates/blog_authorization/login.html
{% extends "base.html" %}

{% block title %}
  Login
{% endblock %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% else %}
      <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}

  <form method="post">
  {% csrf_token %}
    {{ form.as_p }}

  <input type="submit" value="login">
  <input type="hidden" name="next" value="{{ next }}">
  </form>

{% endblock %}

homework_09/blog/blog_authorization/templates/blog_authorization/register.html
{% extends "base.html" %}

{% block title %}
  Register
{% endblock %}

{% block content %}
  <h2>Register</h2>

  <form method="post">
  {% csrf_token %}
    {{ form.as_p }}

  <input type="submit" value="Register">
  <input type="hidden" name="next" value="{{ next }}">
  </form>

{% endblock %}

homework_09/blog/blog_django_app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <link
        href="{% static 'blog/css/bootstrap.min.css' %}"
        type="text/css"
        rel="stylesheet"
    />

    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>

    <style>
      html {
        background: #f6ead4;
      }
      body {
        background: #b4a284;
      }
      h1 {
        font-size: 2em;
      }
      button {
        margin: 4px;
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if request.user.is_authenticated  %}
              <a class="nav-link" href="{% url 'blog_django_app:user_details' pk=request.user.pk %}">My profile</a>
            {% endif %}
            <a class="nav-link" href="{% url 'blog_django_app:users' %}">Users</a>
            <a class="nav-link" href="{% url 'blog_django_app:posts' %}">Posts</a>
            <a class="nav-link" href="{% url 'blog_django_app:post_creation' %}">Create post</a>
            {% if request.user.is_authenticated  %}
              <a class="nav-link me-2" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="nav-link" href="{% url 'register' %}">Register</a>
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    <div class="container my-4">
      {% block content %}
          Base Body
      {% endblock %}
    </div>

    <br>
    <script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>

  </body>
</html>

homework_09/blog/blog_django_app/templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <link
        href="{% static 'blog/css/bootstrap.min.css' %}"
        type="text/css"
        rel="stylesheet"
    />

    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>

    <style>
      html {
        background: #f6ead4;
      }
      body {
        background: #b4a284;
      }
      h1 {
        font-size: 2em;
      }
      button {
        margin: 4px;
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'blog_django_app:users' %}">Users</a>
            <a class="nav-link" href="{% url 'blog_django_app:posts' %}">Posts</a>
          </div>
        </div>
      </div>
    </nav>

    <div class="container my-4">
      {% block body %}
          Base Body
      {% endblock %}
    </div>

    <br>
    <script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>

  </body>
</html>

homework_09/blog/blog_django_app/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Delete post {{ post.title }}
{% endblock %}

{% block content %}
  <h1>Delete post <strong>"{{ post.title }}"</strong>?</h1>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Delete!">
  </form>
  <hr>
  <div>
    <a href="{% url 'blog_django_app:posts' %}">Back to posts list</a>
  </div>
   <div>
    <a href="{% url 'blog_django_app:post_details' post.pk %}">Back to post</a>
  </div>
{% endblock %}

homework_09/blog/blog_django_app/templates/blog/post_creation.html
{% extends 'base.html' %}

{% block title %}
  Create Post
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>

  <hr>
  <div>
    <a href="{% url 'blog_django_app:posts' %}">Back to post</a>
  </div>
{% endblock %}

homework_09/blog/blog_django_app/templates/blog/post_details.html
{% extends 'base.html' %}

{% block title %}
  Post #{{ post.id }}
{% endblock %}

{% block content %}
  <h1>
    Post "{{ post.title|title }}"
    by <a href="{% url 'blog_django_app:user_details' pk=post.user.id %}">{{ post.user.username }}</a>
  </h1>

  <div>
    <p>{{ post.body }}</p>
  </div>

  <br>
  <div>
    <a class="btn btn-dark" href="{% url 'blog_django_app:posts' %}">All posts.</a>
  </div>

  <br>
  <div>
    <a class="btn btn-danger" href="{% url 'blog_django_app:post_delete' pk=post.pk %}">Delete post.</a>
  </div>

{% endblock %}

homework_09/blog/blog_django_app/templates/blog/posts.html
{% extends 'base.html' %}

{% block title %}
  Posts List
{% endblock %}

{% block content %}
  <h1>Posts: </h1>

  {% if post_list %}
    <ul class="list-group">
      {% for post in post_list %}
        <li class="list-group-item">
          <a class="text-decoration-none">
            <strong>
              <a href="{% url 'blog_django_app:post_details' pk=post.id %}">"{{ post.title }}"</a>
            </strong>  by {{ post.user.username }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <div>
      <strong>No posts.</strong>
    </div>
  {% endif %}

  <hr>
  <div>
    <a href="{% url 'blog_django_app:post_creation' %}">Create a new post.</a>
  </div>

{% endblock %}

homework_09/blog/blog_django_app/templates/blog/user_details.html
{% extends 'base.html' %}

{% block title %}
  User #{{ user.id }}
{% endblock %}

{% block content %}
  <h1>
    User {{ user.username }}
  </h1>

  <div>
    <strong>About {{ user.username }}</strong>:
    <p>{{ user.about }}</p>
  </div>

  {% if user_posts %}
    <h2>
      {{ user.username }}'s posts:
    </h2>
    <ul class="list-group">
      {% for post in user_posts %}
        <li class="list-group-item">
          <a class="text-decoration-none" href="{% url 'blog_django_app:post_details' pk=post.id %}">
            {{ post.title }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <div>
      <strong>No posts.</strong>
    </div>
  {% endif %}

  {% if request.user.pk != user.pk %}
    <br>
    <div>
      <a class="btn btn-dark" href="{% url 'blog_django_app:users' %}">All users.</a>
    </div>
  {% endif %}


{% endblock %}

homework_09/blog/blog_django_app/templates/blog/users.html
{% extends 'base.html' %}

{% block title %}
  Users List
{% endblock %}

{% block content %}
  <h1>Users: </h1>

  {% if object_list %}
    <ul class="list-group">
      {% for user in object_list %}
        <li class="list-group-item">
          <a class="text-decoration-none" href="{% url 'blog_django_app:user_details' pk=user.id %}">
            {{ user.username }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <div>
      <strong>No users.</strong>
    </div>
  {% endif %}

{% endblock %}